
import { GoogleGenAI, Modality } from "@google/genai";

const MODEL_NAME = 'gemini-2.5-flash-image';

interface SampleImage {
  before: string;
  after: string;
}

const getBase64Parts = (base64String: string) => {
  const match = base64String.match(/^data:(image\/.+);base64,(.+)$/);
  if (!match) {
    throw new Error('Invalid base64 string format');
  }
  return {
    mimeType: match[1],
    data: match[2],
  };
};

const imageUrlToBase64 = async (url: string): Promise<string> => {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`HTTP error! status: ${response.status}`);
  }
  const blob = await response.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = (error) => reject(error);
    reader.readAsDataURL(blob);
  });
};

export const generateSampleImage = async (
  clothingImageUrl: string,
  modelImageUrl: string,
  backgroundPrompt: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
  }
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const clothingImageBase64 = await imageUrlToBase64(clothingImageUrl);
  const modelImageBase64 = await imageUrlToBase64(modelImageUrl);

  const clothingImageParts = getBase64Parts(clothingImageBase64);
  const modelImageParts = getBase64Parts(modelImageBase64);

  const prompt = `Create a high-quality, photorealistic image for a fashion e-commerce website. The image must feature the model from the second image provided, wearing the clothing item from the first image provided. The background should be: ${backgroundPrompt}. The final image should be stylish, professional, and focus on showcasing the clothing item accurately and appealingly on the specified model.`;
  
  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: clothingImageParts.data,
              mimeType: clothingImageParts.mimeType,
            },
          },
          {
            inlineData: {
                data: modelImageParts.data,
                mimeType: modelImageParts.mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        const mimeType = part.inlineData.mimeType;
        return `data:${mimeType};base64,${base64ImageBytes}`;
      }
    }

    throw new Error("No image was generated by the API.");
  } catch (error) {
    console.error("Error generating sample image with Gemini API:", error);
    throw new Error("Failed to generate the sample image.");
  }
};

export const SAMPLE_DATA = [
  {
    category: 'زنانه',
    items: [
      {
        clothingUrl: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&h=500&fit=crop',
        modelUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop',
        background: 'a clean, minimalist studio background with soft, even lighting'
      },
      {
        clothingUrl: 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=400&h=500&fit=crop',
        modelUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop',
        background: 'a bustling New York City street with blurred background'
      },
    ]
  },
  {
    category: 'مردانه',
    items: [
      {
        clothingUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&h=500&fit=crop',
        modelUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop',
        background: 'a stylish urban rooftop with city skyline in the background'
      },
      {
        clothingUrl: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=400&h=500&fit=crop',
        modelUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop',
        background: 'a modern interior with minimalist furniture'
      },
    ]
  },
  {
    category: 'دخترانه',
    items: [
      {
        clothingUrl: 'https://images.unsplash.com/photo-1503919436766-f2732abb0cac?w=400&h=500&fit=crop',
        modelUrl: 'https://images.unsplash.com/photo-1518632945996-6cb9e69ef14c?w=400&h=500&fit=crop',
        background: 'a serene beach at sunset with golden light'
      },
      {
        clothingUrl: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=400&h=500&fit=crop',
        modelUrl: 'https://images.unsplash.com/photo-1518632945996-6cb9e69ef14c?w=400&h=500&fit=crop',
        background: 'a chic, modern interior with large windows'
      },
    ]
  },
];
